language: c

env:
    matrix:
        - CUDA=7.5-18

before_install:
    # Install CUDA library
    - echo "Installing CUDA library"
    - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDA}_amd64.deb
    - travis_retry sudo dpkg -i cuda-repo-ubuntu1404_${CUDA}_amd64.deb
    - travis_retry sudo apt-get update -qq
    - export CUDA_APT=${CUDA%-*}
    - export CUDA_APT=${CUDA_APT/./-}
    - echo ${CUDA_APT}
    - travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT}
    - travis_retry sudo apt-get clean
    - export CUDA_PATH=/usr/local/cuda-${CUDA%%-*}
    - export LD_LIBRARY_PATH=${CUDA_HOME/lib64:${LD_LIBRARY_PATH}
    - export PATH=${CUDA_HOME}/bin:${PATH}
    - echo ${CUDA_PATH}
script:
    make

after_failure:
    - dmesg
    - ls -R /usr/local/cuda*
